name: Build and Push Multi-Service Images

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_PATIENT: patient-service
  ECR_REPOSITORY_APPOINTMENT: appointment-service

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build & Push Patient
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-tag.outputs.tag }}
        run: |
          docker build -t patient-service ./patient-service
          docker tag patient-service:latest $ECR_REGISTRY/hack/patient-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/hack/patient-service:$IMAGE_TAG

      - name: Build & Push Appointment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-tag.outputs.tag }}
        run: |
          docker build -t appointment-service ./appointment-service
          docker tag appointment-service:latest $ECR_REGISTRY/hack/team4:$IMAGE_TAG
          docker push $ECR_REGISTRY/hack/team4:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # ðŸ”¥ THIS ENABLES MANUAL APPROVAL
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name bayer-eks-dev

      # - name: Deploy to Kubernetes
      #   env:
      #     IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      #   run: |
      #     ECR_REGISTRY=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com

      #     sed -i "s|IMAGE_PATIENT|$ECR_REGISTRY/hack/patient-service:$IMAGE_TAG|g" k8s.yaml
      #     sed -i "s|IMAGE_APPOINTMENT|$ECR_REGISTRY/hack/team4:$IMAGE_TAG|g" k8s.yaml

      #     kubectl apply -f k8s.yaml

      # - name: Build, Tag and Push Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_NAME: hack/patient-service
      #     IMAGE_TAG: latest   # or use ${{ github.sha }}
      #   run: |
      #     echo "Building Docker image...patient-service"
      #     docker build -t $IMAGE_NAME ./patient-service

      #     echo "Tagging image for ECR..."
      #     docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      #     echo "Pushing image to ECR..."
      #     docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # - name: Build, Tag and Push Image for appointment
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_NAME: hack/team4
      #     IMAGE_TAG: latest   # or use ${{ github.sha }}
      #   run: |
      #     echo "Building Docker image...appointment-service"
      #     docker build -t $IMAGE_NAME ./appointment-service

      #     echo "Tagging image for ECR..."
      #     docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      #     echo "Pushing image to ECR..."
      #     docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG