name: Build and Push Multi-Service Images

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_PATIENT: patient-service
  ECR_REPOSITORY_APPOINTMENT: appointment-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # - name: Build & Push Patient Service
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_PATIENT:$IMAGE_TAG ./patient-service
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY_PATIENT:$IMAGE_TAG

      - name: Build, Tag and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: hack/patient-service
          IMAGE_TAG: latest   # or use ${{ github.sha }}
        run: |
          echo "Building Docker image...patient-service"
          docker build -t $IMAGE_NAME ./patient-service

          echo "Tagging image for ECR..."
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Build, Tag and Push Image for appointment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: hack/team4
          IMAGE_TAG: latest   # or use ${{ github.sha }}
        run: |
          echo "Building Docker image...appointment-service"
          docker build -t $IMAGE_NAME ./appointment-service

          echo "Tagging image for ECR..."
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:IMAGE_TAG

          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG